

# This file was *autogenerated* from the file doing_stuff.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_3000 = Integer(3000); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
import csv
import ast
import sage.all as sage

# Read the CSV file
with open('/home/cawilson1/REU2024/REU2024-2/our_data.csv', 'r') as file:
    reader = csv.reader(file)
    rows = list(reader)

# Update the rows with the determinant of the Seifert matrix
i = _sage_const_0 
for row in rows[_sage_const_3000 :]:  # Skip header and example row
    if row[_sage_const_1 ]:  # Check if the Seifert matrix is not empty
        try:
            seifert_matrix = sage.matrix(sage.SR, ast.literal_eval(row[_sage_const_1 ]))
            det_seifert_matrix = seifert_matrix.det()
            row[_sage_const_2 ] = str(det_seifert_matrix)
        except Exception as e:
            print(f"Error processing row {row}: {e}")
            row[_sage_const_2 ] = 'Error'
    print(i, len(seifert_matrix[_sage_const_0 ]), det_seifert_matrix)
    i += _sage_const_1 

# Write the updated rows back to the CSV file
with open('our_data_updated.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(rows)

print("Updated CSV file has been saved as 'knots_updated.csv'")



